name: Run Reddit Scraper Every 12 Hours

on:
  schedule:
    - cron: '0 */12 * * *'   # Every 12 hours UTC
  workflow_dispatch:         # Allow manual trigger from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
      REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Hist_Comm_Git.py
        run: python Hist_Comm_Git.py

      # Optional: auto-commit any output files (e.g., CSV/JSON in /data folder)
      - name: Commit and push updated master CSV
        run: |
          git config user.name "burnsyboy31"
          git config user.email "zachpburns@gmail.com"
          git add -f data/wsb_master_comments.csv
          git commit -m "📊 Auto-update WSB master at $(date)" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main || echo "Nothing to push"
        continue-on-error: true  # avoids failing the job if no changes
