name: Label New Reddit Comments

on:
  schedule:
    - cron: '0 */12 * * *'  # every 6 hours
  workflow_dispatch:

permissions:
  contents: write  # needed to push labeled file back

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install torch transformers pandas

      - name: Run label script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # if using a private model
        run: |
          python label_new_comments.py

      - name: Commit and push updated CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Extract new label count
          count=$(grep -oP '✅ Labeled \K[0-9]+' label_log.txt || echo 0)

          # Stage correct file
          git add data/labeled_comments.csv

          git commit -m "🤖 Labeled $count new Reddit comments on $(date)" || echo "No changes to commit"
          git push
        Shell: bash


